### ISSUE TITLE
[BUG] Parser breaks on `hex""`

### ISSUE THREAD

**Issue by tintinweb** [ConsenSys/solidity-parser-antlr#8]
### Symptom

`ParserError: extraneous input '""' expecting ';' (359:22)`

### Example

https://github.com/summa-tx/bitcoin-spv/blob/c13fd9aa141fc8dc6c56fa1e730a9350ff055e59/solidity/contracts/BTCUtils.sol

```solidity
    function extractOpReturnData(bytes memory _output) internal pure returns (bytes memory) {
        if (_output.keccak256Slice(9, 1) != keccak256(hex"6a")) {
            return hex"";
        }
        bytes memory _dataLen = _output.slice(10, 1);
        return _output.slice(11, bytesToUint(_dataLen));
    }
```

**Comment by GNSPS** [comment]
It should be corrected with this commit: https://github.com/ConsenSys/solidity-parser-antlr/commit/b178319dc052cbe4140137f067554f1f8b2a8fe9

Have you tried upgrading the parser to the latest version? (currently `v0.4.18`)

**Comment by GNSPS** [comment]
I'm closing this but feel free to reopen!
